use std::{
    net::{IpAddr, Ipv6Addr},
    thread,
};

use futures::prelude::*;
use futures::StreamExt;
use tarpc::{
    server::{self, Channel},
    tokio_serde::formats::Json,
};
use tokio::{runtime::Runtime, sync::mpsc};

use service::{spawn, Application, HelloServer, World};

fn main() -> eframe::Result {
    env_logger::init();

    let (gui_tx, gui_rx) = mpsc::channel(32);

    let _hdl = thread::spawn(move || {
        let rt = Runtime::new().unwrap();

        rt.block_on(async move {
            let server_addr = (IpAddr::V6(Ipv6Addr::LOCALHOST), 5000);

            let listener = tarpc::serde_transport::tcp::listen(&server_addr, Json::default)
                .await
                .expect("TODO");

            listener
                // Ignore accept errors.
                .filter_map(|r| future::ready(r.ok()))
                .map(server::BaseChannel::with_defaults)
                // serve is generated by the service attribute. It takes as input any type implementing
                // the generated World trait.
                .map(|channel| {
                    let hello_server: HelloServer = HelloServer {
                        gui_tx: gui_tx.clone(),
                    };
                    channel.execute(hello_server.serve()).for_each(spawn)
                })
                // Max 10 channels.
                .buffer_unordered(10)
                .for_each(|_| async {})
                .await;
        });
    });

    let options = eframe::NativeOptions::default();

    eframe::run_native(
        "My egui App",
        options,
        Box::new(|cc| {
            let app = Application::new(gui_rx);
            Ok(Box::new(app))
        }),
    )
}
